### ISSUE TITLE
Remove `master` from Bioc Package Browser link

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/bioconductor.org#234]
The Bioc Package Browser link near the bottom of landing pages has `master` at the end of it. I think it can just be removed or set to `devel` if needed.

**Comment by lshep** [comment]
it was requested the code browser link be added to the landing pages so better to update.  I'll look at this shortly

**Comment by jwokaty** [comment]
Sorry, maybe my wording is confusing. I just meant to change or remove `master` at the end of the link.

**Comment by lshep** [comment]
what package do you see this in?   For example BiocGenerics actually does show devel and not master in the link?   as does IRanges -- just choosing randomly -- so is there one you actually see that in

**Comment by lshep** [comment]
@jwokaty  can you look at how the VIEWS are being generated again -- this acutally seems like a bug there --  as you can see in https://www.bioconductor.org/packages/release/bioc/VIEWS  the git_branch is showing master instead of RELEASE_3_17  --- if the VIEWS files is corrected than the landing page is corrected
