### ISSUE TITLE
Mention more time zones for the build reports

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioconductor.org#73]
Hi, I never manage to wrap my mind around the bioc build farm timing. 
I aim to submit a PR to https://github.com/Bioconductor/bioconductor.org/blob/master/content/developers/how-to/troubleshoot-build-report.md
which adds more time zones. I am open to opinions whether 
1) inline or as a small table with "pull snapshot / build report" x "time zone" and 
2) which time zone(s). 

Question: Do you edit that page when you switch between EST <-> EDT ? Or is it always 14:30 New York time ?
Or does the reader have to do that DST offset in summer herself ? Or what is an hour between friends ? 
I would like to add Europe (UTC and/or UTC+2 CET) and Asia (UTC+8 CST and/or UTC+9 JST).

**Comment by hpages** [comment]
The big question is which time zones. The choice will necessarily be arbitrary so a little bit unfair.

Continental Europe is 6h ahead of New York.

We don't edit that page when we switch between winter/summer time because the build schedule automatically follows the switch e.g. the daily builds always start at 14:30 NY time / 20:30 Continental Europe time, all year round (except during the few days when one side of the Atlantic ocean switched but not the other side yet).

**Comment by LiNk-NY** [comment]
To avoid choosing, we can use a link that adjust depending on the user's time zone... https://everytimezone.com/
e.g., https://everytimezone.com/s/628974b8

**Comment by hpages** [comment]
Sounds good @LiNk-NY. Want to submit a PR?
